# Generated by Django 4.0.1 on 2022-01-21 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_remove_info_email_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='image',
            new_name='imag',
        ),
    ]
