# Generated by Django 4.0.1 on 2022-01-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_alter_info_imag'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='approval',
            field=models.BooleanField(default=False),
        ),
    ]
