# Generated by Django 4.0.1 on 2022-01-24 08:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_blog_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Date',
            field=models.DateField(default=datetime.datetime(2022, 1, 24, 13, 41, 35, 720807)),
        ),
    ]
